// <auto-generated />
using System;
using CoffeeShops.Orders.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoffeeShops.Orders.API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190120194754_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("CoffeeShops.Orders.API.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientId");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Date");

                    b.Property<DateTime>("DateDelivery");

                    b.Property<string>("ShopId");

                    b.Property<int>("StatusOrder");

                    b.Property<int>("StatusPayment");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CoffeeShops.Orders.API.Models.ProductItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<string>("OrderId");

                    b.Property<string>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CoffeeShops.Orders.API.Models.ProductItem", b =>
                {
                    b.HasOne("CoffeeShops.Orders.API.Models.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
